### ISSUE TITLE
Required "addNet" fix

### ISSUE THREAD

**Issue by TimofeyGritsun** [mvg-internship/utopia-eda#29]
Segmenation fault occurs while running test using addNet() with subsequent use of setGate() method.
The reason is the fact that it is impossible for getSubnetId() to return to the which net gates belong because gates exist in two nets at the same time.

**Comment by ssmolov** [comment]
https://github.com/mvg-internship/utopia-eda/pull/33

**Comment by ssmolov** [comment]
Test from pull request is passed right now.
